name: Nightly

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  check_new_commits:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
  deploy:
    needs: check_new_commits
    if: ${{ needs.check_new_commits.outputs.should_run != 'false' }}
    name: TheListeningRoom
    environment: CI
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare Certificates
        env:
          MAC_DEV_CER: ${{ secrets.MAC_DEV_CER }}
          DEVELOPER_ID_CER: ${{ secrets.DEVELOPER_ID_CER }}
          MAC_DEV_CER_PASSWORD: ${{ secrets.MAC_DEV_CER_PASSWORD }}
          DEVELOPER_ID_CER_PASSWORD: ${{ secrets.DEVELOPER_ID_CER_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          MAC_DEV_CER_PATH=$RUNNER_TEMP/madev.p12
          DEVELOPER_ID_CER_PATH=$RUNNER_TEMP/devid.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          echo -n "$MAC_DEV_CER" | base64 --decode -o "$MAC_DEV_CER_PATH"
          echo -n "$DEVELOPER_ID_CER" | base64 --decode -o "$DEVELOPER_ID_CER_PATH"
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security import $MAC_DEV_CER_PATH -P "$MAC_DEV_CER_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
          security import $DEVELOPER_ID_CER_PATH -P "$DEVELOPER_ID_CER_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
          security list-keychain -d user -s "$KEYCHAIN_PATH"
      - name: Build
        env:
          scheme: ${{ 'TheListeningRoom' }}
          platform: ${{ 'macOS' }}
        run: |
          xcodebuild archive \
            -scheme "$scheme" \
            -project "TheListeningRoom.xcodeproj" \
            -destination "platform=$platform" \
            -archivePath "dist/TheListeningRoom.xcarchive"
      - name: Package
        run: |
          xcodebuild -exportArchive \
            -archivePath "dist/TheListeningRoom.xcarchive" \
            -exportOptionsPlist ".github/workflows/NightlyExportOptions.plist" \
            -exportPath "dist/" \
            -allowProvisioningUpdates
          npm install --global create-dmg
          pushd dist
          create-dmg TheListeningRoom.app --overwrite
          DMGS=$(echo TheListeningRoom*.dmg)
          mv "${DMGS[0]}" "TheListeningRoom.dmg"
          popd
      - name: Notarize
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          NOTARY_PASSWORD: ${{ secrets.NOTARY_PASSWORD }}
        run: |
          xcrun notarytool submit \
            --team-id "$TEAM_ID" \
            --apple-id "$APPLE_ID" \
            --password "$NOTARY_PASSWORD" \
            --wait \
            dist/TheListeningRoom.dmg
          xcrun stapler staple dist/TheListeningRoom.dmg
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'The Listening Room Nightly Release $$'
          prerelease: true
          body: 'Nightly build of main branch'
          files: |
            ./dist/TheListeningRoom.dmg